### ISSUE TITLE
The variable "$WindowsImage" cannot be retrieved because it is not set.

### ISSUE THREAD

**Issue by Drovosek01** [x0nn/Convert-WindowsImage#22]
I downloaded it .the zip archive of the repository with the latest changes, unzipped and did what is written in the readme, but received such an error

```
WriteLogMessage : 2021-10-16T13:20:25 [DESKTOP-FOTEH5P] The variable "$Windows Image" cannot be retrieved because it is
not set.
D:\Convert-WindowsImage-main\Convert-WindowsImage.ps1:2350 sign:13
```

![image](https://user-images.githubusercontent.com/29478700/137589130-79fac87e-8388-41e1-b92e-a4efc5d71ff3.png)

**Comment by suntong** [comment]
Yep, I got that `The variable '$openImage' cannot be retrieved because it has not been set` error, too. 

You beat me to it @Drovosek01, 😀
