### ISSUE TITLE
Error: The variable "$ImageIndex" cannot be retrieved because it is not set.

### ISSUE THREAD

**Issue by Drovosek01** [x0nn/Convert-WindowsImage#26]
`Convert-WindowsImage -SourcePath "D:\21390.2025_arm64_ru-ru_professional_7811e991_convert\21390.2025.210603-0312.CO_RELEASE_SVC_IM_CLIENTPRO_OEMRET_A64FRE_RU-RU.ISO" -VHDFormat "VHDX" -Edition "LIST" -SizeBytes 15GB -DiskLayout "UEFI" -VHDPath "D:\21390.2025_arm64_ru-ru_professional_7811e991_convert\Windows10ARM.vhdx"`

Initially, the creation progress is displayed, but then everything is interrupted and an error is displayed.

![image](https://user-images.githubusercontent.com/29478700/137858672-3a02d434-8db9-4e30-a088-b5c76e0fe815.png)

At the same time , the file .vhdx is being created, but it only has a hidden directory `System Volume Information`

![image](https://user-images.githubusercontent.com/29478700/137857466-d837388f-70e2-451b-be05-8df0c4420f6e.png)

This happens on Windows 10 x86_64. I 'm trying out .ISO image with Windows 10 for ARM to make .vhdx file with Windows 10 ARM.

You can create this one yourself .iso image by downloading files from here (I also checked the box to integrate .NET Framework 3.5): https://uupdump.net/download.php?id=7811e991-621e-4b0c-a066-ee0d4b53eacf&pack=en-us&edition=professional

![image](https://user-images.githubusercontent.com/29478700/137858250-5c82bcc9-8488-4c0f-b7c1-25aec7c01754.png)

**Comment by x0nn** [comment]
variable was not reset after the script finished and so it worked on dev, lol
please retest with release 21H2-3

**Comment by Drovosek01** [comment]
Thanks. I get files from this branch (https://github.com/x0nn/Convert-WindowsImage/tree/release/21H2) and now the .vhdx file is being created (I do not know how working it is, because I do not have a computer on ARM).

But there are a few more problems:
1. The "LIST" line for the "-Edition" argument does not work as described in the README. I have created one .vhdx file, and did not get the output of the list of all editions. I had to find out the Edition using DISM
![image](https://user-images.githubusercontent.com/29478700/137982296-69a178d2-14a4-446f-95e7-b030f443db59.png)

2. The .iso I was working with was Windows 10 ARM64 with a single edition of "Windows 10 Pro".
Even if I pass the string "LALALA" for the "-Edition" argument, the creation process will begin with my .iso file.vhdx and will end without errors and without displaying a list of all editions.
Probably this is due to the fact that there is only 1 edition in it.
It seems to me that some kind of error or warning should appear if I entered the name of a non-existent edition.
![image](https://user-images.githubusercontent.com/29478700/137983933-d7bb5e8d-4bff-49d3-92b7-7cb48ff68308.png)

3. The script does not check the existence of the file specified in the "-vhdpath" argument and immediately creates .a vhdx file with a random name and after creation tries to rename the file and if the rename failed, an error is displayed. (In my case, there was an error "Remove-Item : Cannot delete item" because at the time of renaming, the file .the vhdx that needed to be replaced was mounted in the system).
It is probably correct to check the existence of a file with the same name before starting all processes.
![image](https://user-images.githubusercontent.com/29478700/137983972-bccf5b44-f75a-4df9-8ba8-c2e1327e4798.png)

**Comment by x0nn** [comment]
For 1. and 2. 
- It will print the list, if a -Edition was given but did not match
- It will print a warning choosing the only image if no -Edition was given and only one image available
For 3. #28 handles that

Please retest with latest release commit

**Comment by Drovosek01** [comment]
For 1 and 2 now it's works.

![image](https://user-images.githubusercontent.com/29478700/138006867-862732e2-c764-49de-addd-2e7f153d1f00.png)

Thank you very much!
