### ISSUE TITLE
Cannot add type. The type name 'WIM2VHD.NativeMethods' already exists.

### ISSUE THREAD

**Issue by ztrhgf** [x0nn/Convert-WindowsImage#3]
Command: Convert-WindowsImage -SourcePath "C:\DATA\downloady\Windows_1903.iso" -Edition Professional -VHDPath "C:\DATA\downloady\Windows_1903.vhdx" -DiskLayout UEFI

end with error: Cannot add type. The type name 'WIM2VHD.NativeMethods' already exists.

**Comment by x0nn** [comment]
Add-Type is complicated in my opinion. Try to close the shell and open it again, when you dotsource the script again. Does it help?

**Comment by x0nn** [comment]
no feedback

**Comment by legionliu** [comment]
@x0nn Hello, same issue here, and closing & opening again helps. Thanks!
