### ISSUE TITLE
PS Gallery version not updated

### ISSUE THREAD

**Issue by ReneEChr** [x0nn/Convert-WindowsImage#6]
Hi, 
Great piece of work, i am having great use of your script. Thanks for keeping it updated!

I did recently discover the module on PSGallery and found it made it much easier for me to utilize your script in a vm-builder i am working on, but i ran into a bug that i believe you already fixed.
`
PS>TerminatingError(ForEach-Object): "The variable '$hyperVEnabled' cannot be retrieved because it has not been set."
Convert-WindowsImage : The variable '$hyperVEnabled' cannot be retrieved because it has not been set.
`
Any chance that powershell gallery (https://www.powershellgallery.com/packages/Convert-WindowsImage/10.0) can get updated with this github version ?

**Comment by x0nn** [comment]
Hi,

please star if you like the script. This way I can track how much people are using it. The Powershell gallery version is uploaded by Microsoft, but I can merge the changes I made and open a pull request @ https://github.com/MicrosoftDocs/Virtualization-Documentation, to get the changes there.

Do you have further information, when the error occurs? OS Version, Powershell Version, Parameters?

**Comment by ReneEChr** [comment]
Hi, 
The error is not present in the github version(at least for me), only the one in psgallery.
I have used the psgallery module on W2019-Std, PS5.1 and W10, PS5.1.
Not using ISE.
As for parameters, this is an example "-Sourcepath 'c:\temp\w2019.wim' -vhdpath 'c:\temp\w2019.vhdx' -sizebytes 100GB -DiskLayout 'UEFI' -UnattendPath 'c:\temp\w2019.xml' "

My workaround is simply making my code downloading the github version as needed instead of using the install-module. 
It would off cause be a lot easier just to fetch it with  install-module :)

**Comment by x0nn** [comment]
First pull request is open for merging back the bugfixes:
https://github.com/MicrosoftDocs/Virtualization-Documentation/pull/1342

FTR - It seems that microsoft has several Scripts
- psm1 from above - seems a good upstream source for me, if they merge improvements
- ps1 from above - seems like an old version
- psm1 from powershell gallery (seems like commit 2bc48278e48915577149ae6c1ae1f4cb9c52cc8c from above)

If they merge the changes, I will update this code to upstream and merge my features and set psd version to 10.1. After that its up to microsoft to update the ps gallery module. Meanwhile I will add a second script to the gallery under a similar name.

**Comment by Nirmal4G** [comment]
I want to clarify that @microsoft is not managing the PSGallery version. I've uploaded it for convenience. I'm also updating the script recently, as it broke my testing pipeline.

Will upload the new version in a few days. 

> Sorry for the confusion. I didn't want to take credit for something I didn't write. So I didn't list myself as the author.

**Comment by x0nn** [comment]
@Nirmal4G did you updated the Module? Maybe there is a way to automate this process within this repo. Please tell me, if this is a option for you?

**Comment by x0nn** [comment]
Hi,

there is no progress in this @Nirmal4G . Since I do not have control over the upload to the gallery I have to close this, but left a comment here https://github.com/MicrosoftDocs/Virtualization-Documentation/pull/1342
