### ISSUE TITLE
Script doing nothing at all

### ISSUE THREAD

**Issue by althurman** [x0nn/Convert-WindowsImage#8]
Hello All,

I am trying to use the available Microsoft script to convert my wim file to a vhd file 

When I simply run the script from command line it does nothing at all. I have tried calling with many different params. The simplest just trying to launch the GUI

Convert-WindowsImage.ps1 -ShowUI
 
Am I missing something? Anybody seen this before? I don't even know how to start debugging since nothing at all shows in the command line

**Comment by suntong** [comment]
From https://gallery.technet.microsoft.com/scriptcenter/Convert-WindowsImageps1-0fe23a8f

- UI is deprecated. This was a tough decision but I don't have enough skills and time to maintain it and support with the new features I added over time.

and most importantly, 

- The script is now a Function! You have to load it first (aka “dot-source”) and then call by its name, without extension.Please refer to the Examples section below for a code sample.
