### ISSUE TITLE
Write-W2VError: Cannot bind parameter 'ForegroundColor'

### ISSUE THREAD

**Issue by suntong** [x0nn/Convert-WindowsImage#9]
Hi @x0nn, 

I'm really glad to have found your updated script here as the one on MS technet gallery is not working for me. The script here no longer has that problem, but the following is what I get, when running it from within PowerShell ISE:

```
Windows(R) Image to Virtual Hard Disk Converter for Windows(R) 10
Copyright (C) Microsoft Corporation.  All rights reserved.
Version 10.0.14278.1000.amd64fre.rs1_es_media.160201-1707

INFO   : Done.
Write-W2VError : Cannot bind parameter 'ForegroundColor'. Cannot convert the "#FFFF9494" value of type "System.Windows.Media.Color" to type "System.ConsoleColor".
At line:2393 char:13
+             Write-W2VError $_
+             ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-W2VError], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Write-W2VError
```

Does the "INFO   : Done" mean I'm all set, or the `Write-W2VError` hints there are still something wrong? 

Thx

**Comment by suntong** [comment]
Ops, found from https://github.com/x0nn/Convert-WindowsImage/issues/5 that 

> Powershell ISE is not supported

But please do support it or remote sign your script. Here is the hint why --

```
>.  .\Convert-WindowsImage.ps1
. : File .\Convert-WindowsImage.ps1 cannot be loaded. The file
.\Convert-WindowsImage.ps1 is not digitally signed. You cannot run this script on the
current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\Convert-WindowsImage.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    RemoteSigned
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    Unrestricted
```

with a policy of `MachinePolicy` overriding everything, there is no other way for me to run your script. So, please support Powershell ISE.

**Comment by suntong** [comment]
The run is not successful -- looking at the generated VHD file with  DISKPART, I get:

`There are no partitions on this disk to show.`

**Comment by x0nn** [comment]
This decision is in line with Microsoft. The PowerShell ISE is no longer in active feature development. As a shipping component of Windows, it continues to be officially supported for security and high-priority servicing fixes. We currently have no plans to remove the ISE from Windows.

There is no support for the ISE in PowerShell v6 and beyond. Users looking for replacement for the ISE should use Visual Studio Code with the PowerShell Extension.

[https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/whats-new/what-s-new-in-the-powershell-50-ise?view=powershell-7](url)

If you need ISE-Support a pull request is always welcome.
